USE login_schema;
CREATE TABLE IF NOT EXISTS logins(
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(45) NOT NULL,
   password VARCHAR(255) NOT NULL,
   created_at DATETIME DEFAULT NOW(),
   updated_at DATETIME DEFAULT NOW()
) ENGINE=INNODB;